# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#redirect: https://hugouchoasborges.notion.site

title: Hugo Borges
email: hugouchoas@outlook.com
description: >-                       # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this line in _config.yml. 
  It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl:                              # the subpath of your site, e.g. /blog
url:                              # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  hugouchoasborges
skills: Unity Game Developer

about:
  p1: Unity Game Developer. Computer Engineer at Federal University of Itajubá - UNIFEI.
  p2: Working experience in Unity, GIT version control and all that good stuff.
  button_text: See Full Resume
  button_link: /resume

# Header Settings
header:
  set_resume: true                   # Display resume? 
  set_blog: true                    # Display blog? 
  social: Contact and Networks
  header_bg: background.jpg          # Header background Image
  header_bg_title: <a href='http://www.freepik.com'>Background image Designed by Freepik</a>

# Footer settings
footer:                               #Footer Headers
  copyright: hugouchoasborges
  location: Location
  social: Contact and Networks
  credits: ABOUT THIS WEBSITE
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# For more icons look at http://fontawesome.io/icons/#brand
social:
  - title: linkedin
    url: https://www.linkedin.com/in/hugo-uchoas-borges/
  - title: github
    url: http://github.com/hugouchoasborges
  - title: facebook
    url: https://www.facebook.com/hugo.uchoas.borges
  - title: instagram
    url: https://www.instagram.com/hugo.uchoas.borges/
  - title: itch-io
    url: https://hugouchoasborges.itch.io/
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll

# Postal address (add as many lines as necessary)
address:
  #- line: Queluz - SP
  - line: Brazil

# Credits content
credits: 'Freelancer is an open source, free to use Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
    sass_dir: _sass
    style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# RESUME SECTION
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: 3C5560 #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar  
